---
title: "What is your blogpost title? Add it here??"
subtitle: "Assignment 4 ETC5512"
author: "Who are you?? Add your name here"
format: html
editor: visual
---

::: panel-tabset
<!-- Task 1 Tab: Data and Documenting -->

# Data Details

## Main Question

How has the balance between wild-caught fisheries and aquaculture production in Australia changed over time?

## Sub-problem

1.  Which species categories are most responsible for the growth in aquaculture production?

2.  Has Australia undergone a structural shift from capture fisheries toward aquaculture at the national level since 2000?

### Reason

-   Significance: Australian is a major fishing nation, the research could related with food sustainability and marine environmental policy.

-   Personal: Interested to environmental policy and fishery.

## Data description

<!-- Task 2 Tab: Writing your blogpost -->

## Blog post

### What's in this section

Here is where you should write your blogpost! (Task 2)

### Blogpost Structure

There is no strict structure for you to follow. However, here is a skeleton structure you may find helpful.

1.  Title (is set at the top of this document)
2.  Motivation\
3.  Data\
4.  Analysis\
5.  Conclusions\
6.  References

<!-- Task 3 Tab: Behind the Scenes -  -->

## Behind the Scenes

### What's in this section

Here is where you should tell us about your reflection on your analysis (Task 3).

Again, these are the details about **your** perspective and the gritty details behind the scenes of your analysis.
:::
